Add reply list
CMPUT301W21T03/Experiment-Automata pull request #108
Opened 2021-03-20 23:10 UTC by TurtleSquad007

As per profs request replies can now be nested

2021-03-21 08:21 UTC, giancarlopernudisegura requested changes
**Bug**: Question and replies disappear
**How to recreate**: Make a question, possibly add some replies. Go back to the experiment details page. Click on the Q&A button. Click on the reply button and the question disappears.

2021-03-22 04:30 UTC, giancarlopernudisegura requested changes
add the javadoc argument info for the update function in SingleQuestionDisplay

2021-03-22 04:51 UTC, TurtleSquad007 commented
Done!

2021-03-22 05:58 UTC, giancarlopernudisegura approved these changes

2021-03-22 05:58 UTC, merged