removed unused fields from user
CMPUT301W21T03/Experiment-Automata pull request #181
Opened 2021-04-07 15:22 UTC by TurtleSquad007

2021-04-07 16:37 UTC, giancarlopernudisegura reviewed
What is this empty class?

2021-04-07 16:45 UTC, TurtleSquad007 commented
It's what will eventually becomes the user tests. I stopped working on it when class started so it's empty.

2021-04-08 17:02 UTC, Pegmode commented on code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
> -    protected void updateFromFirestore() {
This is a major change. How did you end up handling this?

2021-04-08 17:14 UTC, TurtleSquad007 commented on code/app/src/main/java/com/example/experiment_automata/backend/users/User.java
> -    protected void updateFromFirestore() {
Not sure what you mean. Like how did I remove the user from talking to firebase

2021-04-08 17:25 UTC, Pegmode requested changes

2021-04-08 17:25 UTC, Pegmode commented on code/app/src/main/java/com/example/experiment_automata/backend/users/UserManager.java
>      public static UserManager getInstance() {
This line is causing errors.

`Experiment-Automata\code\app\src\main\java\com\example\experiment_automata\backend\users\UserManager.java:49: error: illegal start of expression
    public static UserManager getInstance() {
    ^`

2021-04-08 18:01 UTC, Pegmode approved these changes
Issues have been fixed

2021-04-08 18:01 UTC, merged