Subscription fragment
CMPUT301W21T03/Experiment-Automata pull request #71
Opened 2021-03-08 19:55 UTC by musichead42

In this code, I created an Activity for Subscriptions to be shown as well as creating a custom SubscriptionAdapter so that we can view the necessary parts of each experiment.

2021-03-08 22:50 UTC, giancarlopernudisegura requested changes
Please fix the experiment layout. The activity label is overlapping the name label. Please ensure that everything is properly aligned.

![android studio screenshot](https://i.gyazo.com/0f109fe457ff04487bb35ac18cce9f6f.png)

2021-03-08 23:09 UTC, musichead42 commented
Fix has been made

2021-03-09 00:01 UTC, giancarlopernudisegura requested changes
Could you also make the padding around the edges of the screen 8dp to make them all the same?

2021-03-09 00:11 UTC, giancarlopernudisegura approved these changes

2021-03-09 00:11 UTC, merged